# Generated by Django 3.2.9 on 2021-11-26 15:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='add_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='products',
            name='type',
            field=models.CharField(choices=[('1', 'Bánh mặn'), ('2', 'Bánh ngọt'), ('3', 'Dụng cụ làm bánh')], default='0', max_length=200),
        ),
    ]
