# Generated by Django 3.2.9 on 2021-11-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20211126_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='type',
            field=models.CharField(choices=[('Bánh mặn', 'Bánh mặn'), ('Bánh ngọt', 'Bánh ngọt'), ('Dụng cụ làm bánh', 'Dụng cụ làm bánh')], default='Bánh mặn', max_length=200),
        ),
    ]
